[package]
name = "os_log"
version = "0.1.0"
authors = ["Søren Mortensen <soren@sorenmortensen.com>"]
build = "build.rs"

[dependencies]
log = { version = "0.4", features = ["std"] }

[build-dependencies]
bindgen = "0.37"
