[package]
name = "oslog"
version = "0.1.0"
authors = ["Søren Mortensen <soren@sorenmortensen.com>"]
edition = "2018"

[dependencies]
log = { version = "0.4", features = ["std"] }
oslog-sys = { path = "../oslog-sys" }
