[package]
name = "simple"
version = "0.1.0"
authors = ["Søren Mortensen <soren@sorenmortensen.com>"]
edition = "2018"

[dependencies]
oslog = { path = "../../oslog" }

[[example]]
name = "simple"
path = "src/main.rs"